SELECT
    ITEMNMBR,
    DUEDATE,
    ORDERNUMBER,
    TRY_CONVERT(DATE, DUEDATE) AS EventDate,
    COALESCE(TRY_CAST(BEG_BAL AS DECIMAL(18, 5)), 0.0) AS BEG_BAL_clean,
    COALESCE(TRY_CAST("PO's" AS DECIMAL(18, 5)), 0.0) AS POs_clean,
    COALESCE(TRY_CAST(Remaining AS DECIMAL(18, 5)), 0.0) AS Remaining_clean,
    COALESCE(TRY_CAST(Deductions AS DECIMAL(18, 5)), 0.0) AS Deductions_clean,
    COALESCE(TRY_CAST(Expiry AS DECIMAL(18, 5)), 0.0) AS Expiry_clean,
    COALESCE(TRY_CAST(Running_Balance AS DECIMAL(18, 5)), 0.0) AS Source_Running_Balance
FROM dbo.ETB_PAB_AUTO
WHERE TRY_CONVERT(DATE, DUEDATE) IS NOT NULL
    AND TRIM(ITEMNMBR) NOT LIKE '60.%'
    AND TRIM(ITEMNMBR) NOT LIKE '70.%'
    AND TRIM(COALESCE(STSDESCR, '')) <> 'Partially Received';
