-- Synthetic Test Data for Rolyat Unit Tests
-- Insert into ETB_PAB_AUTO and ETB_WC_INV

USE [MED]
GO

-- Clear existing test data
DELETE FROM ETB_PAB_AUTO WHERE ORDERNUMBER LIKE 'TEST_%'
DELETE FROM ETB_WC_INV WHERE Item_Number LIKE 'TEST_%'

-- Test Data for WC Demand Deprecation
INSERT INTO ETB_PAB_AUTO (
    ORDERNUMBER, ITEMNMBR, WCID_From_MO, Construct, Date + Expiry, Deductions, Remaining, Expiry, SITE, STSDESCR
) VALUES
('TEST_ORDER1', 'TEST_ITEM1', 'WC-W1', '297', DATEADD(DAY, 10, GETDATE()), 0, 100, 0, 'SITE1', 'Open'),
('TEST_ORDER2', 'TEST_ITEM1', 'WC-W1', '297', DATEADD(DAY, 25, GETDATE()), 0, 100, 0, 'SITE1', 'Open')

-- WC Inventory for TEST_ITEM1
INSERT INTO ETB_WC_INV (
    Item_Number, SITE, QTY_Available, DATERECD, LOT_Number, EXPNDATE
) VALUES
('TEST_ITEM1', 'WC-W1', 50, DATEADD(DAY, -10, GETDATE()), 'LOT1', DATEADD(DAY, 30, GETDATE()))

-- Test Data for Degradation
INSERT INTO ETB_PAB_AUTO (
    ORDERNUMBER, ITEMNMBR, WCID_From_MO, Construct, Date + Expiry, Deductions, Remaining, Expiry, SITE, STSDESCR
) VALUES
('TEST_DEG15', 'TEST_DEG', 'WC-W1', '297', DATEADD(DAY, 10, GETDATE()), 0, 100, 0, 'SITE1', 'Open'),
('TEST_DEG45', 'TEST_DEG', 'WC-W1', '297', DATEADD(DAY, 10, GETDATE()), 0, 100, 0, 'SITE1', 'Open'),
('TEST_DEG95', 'TEST_DEG', 'WC-W1', '297', DATEADD(DAY, 10, GETDATE()), 0, 100, 0, 'SITE1', 'Open')

INSERT INTO ETB_WC_INV (
    Item_Number, SITE, QTY_Available, DATERECD, LOT_Number, EXPNDATE
) VALUES
('TEST_DEG', 'WC-W1', 100, DATEADD(DAY, -15, GETDATE()), 'LOT_DEG15', DATEADD(DAY, 30, GETDATE())),
('TEST_DEG', 'WC-W1', 100, DATEADD(DAY, -45, GETDATE()), 'LOT_DEG45', DATEADD(DAY, 30, GETDATE())),
('TEST_DEG', 'WC-W1', 100, DATEADD(DAY, -95, GETDATE()), 'LOT_DEG95', DATEADD(DAY, 30, GETDATE()))

-- Test Data for Double Allocation
INSERT INTO ETB_PAB_AUTO (
    ORDERNUMBER, ITEMNMBR, WCID_From_MO, Construct, Date + Expiry, Deductions, Remaining, Expiry, SITE, STSDESCR
) VALUES
('TEST_DOUBLE1', 'TEST_DOUBLE', 'WC-W1', '297', DATEADD(DAY, 10, GETDATE()), 0, 60, 0, 'SITE1', 'Open'),
('TEST_DOUBLE2', 'TEST_DOUBLE', 'WC-W1', '297', DATEADD(DAY, 10, GETDATE()), 0, 60, 0, 'SITE1', 'Open')

INSERT INTO ETB_WC_INV (
    Item_Number, SITE, QTY_Available, DATERECD, LOT_Number, EXPNDATE
) VALUES
('TEST_DOUBLE', 'WC-W1', 100, DATEADD(DAY, -10, GETDATE()), 'LOT_DOUBLE', DATEADD(DAY, 30, GETDATE()))

-- Test Data for Running Balance
INSERT INTO ETB_PAB_AUTO (
    ORDERNUMBER, ITEMNMBR, WCID_From_MO, Construct, Date + Expiry, BEG_BAL, PO's, Deductions, Remaining, Expiry, SITE, STSDESCR
) VALUES
('TEST_BAL1', 'TEST_BAL', 'WC-W1', '297', DATEADD(DAY, 1, GETDATE()), 200, 0, 0, 50, 0, 'SITE1', 'Open'),
('TEST_BAL2', 'TEST_BAL', 'WC-W1', '297', DATEADD(DAY, 2, GETDATE()), 0, 100, 0, 0, 0, 'SITE1', 'Open'),
('TEST_BAL3', 'TEST_BAL', 'WC-W1', '297', DATEADD(DAY, 3, GETDATE()), 0, 0, 0, 80, 0, 'SITE1', 'Open')

GO