-- Run this in SSMS to get actual column names for IV00300
SELECT COLUMN_NAME 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'IV00300' 
ORDER BY ORDINAL_POSITION;

-- Also check IV00101 (item master)
SELECT COLUMN_NAME 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'IV00101' 
ORDER BY ORDINAL_POSITION;
