-- Run this in SSMS to discover actual column names

-- For Prosenthal_INV_BIN_QTY_wQTYTYPE:
SELECT COLUMN_NAME 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'Prosenthal_INV_BIN_QTY_wQTYTYPE' 
ORDER BY ORDINAL_POSITION;

-- For EXT_BINTYPE:
SELECT COLUMN_NAME 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'EXT_BINTYPE' 
ORDER BY ORDINAL_POSITION;
