-- Run this in SSMS to discover the actual column names in ETB_PAB_AUTO
SELECT COLUMN_NAME 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'ETB_PAB_AUTO' 
ORDER BY ORDINAL_POSITION;

-- Alternative: Get column names and data types
SELECT 
    c.COLUMN_NAME,
    c.DATA_TYPE,
    c.CHARACTER_MAXIMUM_LENGTH,
    c.NUMERIC_PRECISION,
    c.NUMERIC_SCALE
FROM INFORMATION_SCHEMA.COLUMNS c
WHERE c.TABLE_NAME = 'ETB_PAB_AUTO'
ORDER BY c.ORDINAL_POSITION;

-- Or check if table exists at all
SELECT TABLE_NAME 
FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_NAME = 'ETB_PAB_AUTO';
